# 演示用家如何使用配方選擇 Rime 輸入方案、自定義配置
# 多用戶使用時可各自按照 GitHub 帳號命名配方清單文件

extend = [
  { path = "rime.toml" },
  { path = "preset-recipes.toml" },
  { path = "grammar.toml" },
]

[tasks.recipes]
dependencies = [
  "Rx-prelude",
  "Rx-luna-pinyin",
  "customize-luna-pinyin",
]

[tasks.customize-luna-pinyin]
description = "自定義：明月拼音方案的可選功能"
env = {SCHEMA = "luna_pinyin"}
run_task = { name = [
  # "use-emoji",
  "use-grammar",
  # "use-symbols",
] }
